{{- if .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName | default (printf "%s-db-secret" .Release.Name) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-100"
type: Opaque
data:
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | b64enc }}
  {{- end }}